/*
 * This source file was generated by the Gradle 'init' task
 */
package hms;

import hms.manager.AppointmentManager;
import hms.manager.InventoryManager;
import hms.manager.ManagerContext;
import hms.manager.PrescriptionManager;
import hms.manager.UserManager;
import hms.system.ISystem;
import hms.system.LoginSystem;
import hms.ui.Prompt;

/**
 * The initializer and exiting point for the whole system.
 * This class will redirect the user to the LoginSystem when it is done initializing the system.
 */
public class App {
    private static final String PATIENT_REPO_FILEPATH = "data/patients.csv";
    private static final String DOCTOR_REPO_FILEPATH = "data/doctors.csv";
    private static final String PHARMACIST_REPO_FILEPATH = "data/pharmacists.csv";
    private static final String ADMIN_REPO_FILEPATH = "data/admins.csv";
    private static final String APPOINTMENT_REPO_FILEPATH = "data/appointments.csv";
    private static final String PRESCRIPTION_REPO_FILEPATH = "data/prescriptions.csv";
    private static final String INVENTORY_REPO_FILEPATH = "data/inventory.csv";

    private boolean isInitialized = false;
    private ISystem currentSystem = null;

    /**
     * Initialize the system by loading all data from the external csv file.
     * Fill all objects with relevant data.
     * Initialize the manager context to grant access of all objects to other relevant objects.
     */
    public void initialize() {
        if (isInitialized) return;

        ManagerContext ctx = new ManagerContext();

        ctx.addManager(UserManager.class,
            new UserManager(ctx,
                PATIENT_REPO_FILEPATH, 
                DOCTOR_REPO_FILEPATH, 
                PHARMACIST_REPO_FILEPATH, 
                ADMIN_REPO_FILEPATH
            )
        );

        ctx.addManager(AppointmentManager.class, new AppointmentManager(ctx, APPOINTMENT_REPO_FILEPATH));
        ctx.addManager(PrescriptionManager.class, new PrescriptionManager(ctx, PRESCRIPTION_REPO_FILEPATH));
        ctx.addManager(InventoryManager.class, new InventoryManager(ctx, INVENTORY_REPO_FILEPATH));

        currentSystem = new LoginSystem(ctx);

        // Add a shutdown hook to save data
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Saving data...");
            // ctx.save(); // Temporarily disabled for testing
        }));

        isInitialized = true;
    }

    /**
     * Start running the system after initializing it. 
     * Raise error if the system is not initialized correctly.
     */
    public void run() {
        if (!isInitialized){
            throw new IllegalStateException("HMS not initialized");
        }

        while (currentSystem != null) {
            currentSystem = currentSystem.run();
            
            // Pause before continuing
            Prompt.getStringInput("Press Enter to continue...");

            // Clear the console
            System.out.print("\033[H\033[2J");
        }

        System.out.println("Exiting HMS Application");
    }
}
