package hms.common.id;

import hms.common.IModel;

/**
 * Generates unique IDs for models.
 * The generated IDs are prefixed with a two-letter code that identifies the model type.
 * The suffix is a number that is unique to the model type (minimum 4 digits).
 */
public class IdManager {
    /**
     * Generates a unique ID for the provided class.
     * The ID is generated by combining the class prefix and a unique suffix.
     * The suffix is generated by incrementing the current suffix for the class.
     * 
     * @param clazz The class to generate
     * @return A unique ID for the class
     */
    public static String generateId(Class<? extends IModel> clazz) {
        String prefix = IdParser.getIdPrefix(clazz);
        String suffix = String.format("%04d", IdRegistry.getNextIdSuffix(clazz));

        return prefix + suffix;
    }

    /**
     * Registers a class with the ID manager.
     * This method should be called for each class that requires a unique ID.
     * 
     * @param clazz The class to register
     * @param prefix The prefix to use for the class
     */
    public static void registerClass(Class<? extends IModel> clazz, String prefix) {
        IdRegistry.addClass(clazz);
        IdParser.addClass(clazz, prefix);
    }
}